# -*- coding: utf-8 -*-
"""
Az ötletbank NEM IRODALMI területeinek saját megfogalmazású sorai.

MIÉRT: a külső világ, a matematika, a rajzolás-festés, a hallás-ritmus és a
mozgás javaslatai szó szerint a „Tappancs" kiadványból kerültek az ötletbankba
(`tools/tappancs_otletek.py`). A szerzői jog a megfogalmazást védi, a
tevékenység gondolatát nem. Itt ugyanaz a tevékenység szerepel, más szavakkal.

A HALLÁS-RITMUS soroknál a dal- és mondókacímek maradnak — azok népköltési
alkotások címei, amelyek önmagukban nem állnak védelem alatt —, csak a sor végi
fejlesztési cél fogalmazódik újra.

A kulcs a régi sor rövid ujjlenyomata (sha1 első 8 jegye), így a magyar szöveget
nem kell kulcsként átgépelni.
"""

from __future__ import annotations

UJ_OTLET: dict[str, str] = {
    # ===================== HALLÁS, RITMUS =====================
    "04f7a7d8": "Ciróka, maróka… Ég a gyertya ég… Hallásfejlesztés: honnan szól a csengő?",
    "b61cd820": "Ciróka, maróka… Fehér karácsony… Széken ülve, helyben topogunk az egyenletes lüktetésre",
    "932d337b": "Fáj a kutyámnak a lába… Cicukám, kelj fel… Az egyenletes lüktetést dalon érezzük meg",
    "109f7489": "Egy, begy, tyúkbegy… Kis, kis kígyó… Az egyenletes lüktetést járással és tapssal jelezzük",
    "02256378": "Cicuska, macuska… Sánta róka… Miben más a lüktetés és a ritmus, és hogyan függnek össze?",
    "77c93535": "Sárga rózsa, vadvirág… Ilyen cica mellett… Saját hangszerekből ritmuszenekart alakítunk",
    "155a82c1": "Sárga rózsa, vadvirág… Erzsébet asszony… Saját hangszerekből ritmuszenekart alakítunk",
    "425ea4a1": "Kicsi kocsi, három csacsi… Erzsébet asszony… Saját hangszerekből ritmuszenekart alakítunk",
    "efe4933a": "Pörcös pogácsa… Kicsi vagyok… A magas és a mély hang megfigyelése",
    "d6388093": "Sírjunk, ríjunk… Most viszik… A magas és a mély hangot mondókán érzékeltetjük",
    "41900c46": "Éliás, Tóbiás… Süssünk… A magas és a mély hangot ismert dalon figyeljük meg",
    "2156ab25": "Egy kis malac… Hopp, mókuska… A halkat és a hangosat egyszerű dalokon érzékeltetjük",
    "4d7fde4e": "Benn a bárány… A halkat és a hangosat mondókán érzékeltetjük",
    "363ab8fb": "Benn a bárány… A halkat és a hangosat dalon érzékeltetjük",
    "527cfb93": "Adjon isten… Tüzet viszek… Ritmust visszhangzunk ismert dalra",
    "d3c42c07": "Adjon isten… Négy vándor jár… Ritmusvisszhang játék, saját kitalált szöveggel",
    "1628e183": "Mackó brummog… Mackó, mackó… Miben más a gyors és a lassú?",
    "72c2a38d": "Brum-brum, Brúnó… Mackó, mackó… A gyors és a lassú különbsége önálló énekléssel",
    "61415fe6": "Kipp, kopp kalapács… Egy kis malac… Hegedül a kisegér… Szőjünk, fonjunk kendőt… Ritmusvisszhang játék",
    "7f5fff98": "Jákobnak volt hat fia… Megy a kocsi… Szőjünk, fonjunk kendőt… Ritmusvisszhang játék",
    "6b1baefe": "Jákobnak volt hat fia… Szőjünk, fonjunk kendőt… Zíbor, zábor… Ritmusvisszhang játék",
    "2511d1d0": "Gyermekek, gyermekek… Fáj a kutyámnak a lába… Csivirítem… Ritmuszenekart alakítunk",
    "08c51ad9": "Kicsi üst… Hej, meszelő… Ritmuszenekart alakítunk",
    "2c415649": "Dolgozni szaporán… Ti csak esztek… Kőketánc… Ritmuszenekart alakítunk",
    "a5951d03": "Nyuszi ül a fűben… Úgy viruljanak a lányok… Mi szél hozott, kis futár… A gyorsat és a lassút metronómmal érzékeltetjük",
    "0a4eb565": "Mi szél hozott, kis futár… Benn a bárány… A gyorsat és a lassút metronómmal érzékeltetjük",
    "d9fdce1e": "Úgy viruljanak a lányok… Mi szél hozott, kis futár… Benn a bárány… A gyorsat és a lassút metronómmal érzékeltetjük",
    "fae947b8": "Én is pisze… Báránykának… Sarkon topogunk helyben, az egyenletes lüktetésre",
    "64728f4a": "Én is pisze… A karácsony… Ritmusmotívumokat tapsolunk vissza",
    "a69ce8ba": "Hipp, hopp… Ezüstfenyő… Ritmust visszhangzunk szöveges motívumokra",
    "b254793c": "Tekereg a szél… A halkat és a hangosat mondókán érzékeltetjük",
    "ee6ef7b3": "Hopp, mókuska… Felismerjük a halk és a hangos közti különbséget",
    "a64457f2": "Ősz szele zümmög… Esik az eső… Énekeljük el halkan, majd hangosan",
    "66ce046b": "Kicsi kocsi… Sári néni utazik… Az egyenletes lüktetést ritmusbottal jelezzük",
    "912eb19c": "Kocsit, kocsit, komámasszony… Sári néni utazik… Jön a kocsi… Dallambújtatás, közben motívumot váltunk",
    "1f182f05": "Megy a kocsi… Most jöttem Bécsből… János úr készül… Dallambújtatás rövidebb és hosszabb egységgel",
    "004e6807": "Gólya viszi… Egyszerű dallamfordulatot énekelünk vissza",
    "de56912d": "Héja, héja… Fecskét látok… Dallammotívumot énekelünk vissza",
    "a8476570": "Egyszer egy erdőben… Gólya, gólya… Dallammotívum visszaéneklése saját szöveggel, együtt és egyenként",
    "300c809b": "Gyí, paci, paripa… Aki nem lép egyszerre… János úr készül… Egyszerű ritmushangszereket használunk",
    "86455a8a": "Réce, ruca… Egyél, libám… A halkat és a hangosat mondókán érzékeltetjük",
    "3eb89645": "Elesett a lúd… Száz liba… Hatan vannak… A halkat és a hangosat dalon, kézmozdulattal jelezzük",
    "a209097d": "Ilyen cica mellett… Tüzet viszek… Dallamot visszhangzunk egymásnak",
    "7bb699b3": "Lóg a lába… Recse, recse, pogácsa… Dallamot visszhangzunk egymásnak",
    "8473c25f": "Elvesztettem zsebkendőmet… Dallamvisszhang játék saját kitalált dallammal",
    "b3849f7c": "Gyermekek, gyermekek… Az egyenletes lüktetést mozdulattal jelezzük",
    "46e5077a": "Hej, a sályi piacon… Én elmentem… Kiemeljük a dalok ritmusát",
    "c42419b3": "Itt kopog, ott kopog… A magas és a mély hangot beszéddel érzékeltetjük",
    "a321ad4d": "Hull a pelyhes… Télapó itt van… A magas és a mély hangot mondókán érzékeltetjük",
    "e98d53ff": "Apacuka, fundaluka… Pattanj, pajtás… A magas és a mély hangot furulyán és dalon érzékeltetjük",
    "28577d0e": "Fussunk, szaladjunk… Egyszerű ritmushangszereket használunk",
    "da6fd021": "Hüvelykujjam almafa… Lipem, lopom a szőlőt… Felismerjük egymás hangját",
    "758cc3dc": "A kálói szőlőbe… Körtéfa, körtéfa… Az egyenletes lüktetést mozgással fejezzük ki",
    "eb8cdeb1": "Lopják az úr szőlőjét… Ősz szele zümmög… Érzékeltetjük, miben más a lüktetés és a ritmus",
    "66dd7fe8": "Kiszáradt a diófa… Egyszerű ritmushangszereket használunk",
    "ff2ec1b3": "Itt a köcsög… Kiszáradt a diófa… Megfigyeljük a halkat és a hangosat",
    "74845438": "De jó a dió… Csicseriborsó, bablencse… Megfigyeljük a halkat és a hangosat éneklés közben",
    "3843e64d": "Dombon törik a diót… A halkat és a hangosat többféleképpen érzékeltetjük",
    "5fdff712": "Koszorú, koszorú… Az egyenletes lüktetést mondókán érzékeltetjük",
    "8db57f85": "Kaszálj, Pista… Koszorú, koszorú… Kiemeljük a dalok és a mondókák ritmusát",
    "83b00f74": "Hervad már a lombnak… Kőketánc… Ritmusról ismerjük fel a dallamot",
    "7893ddc1": "Én is pisze, te is pisze… Koszorú, koszorú… Az egyenletes lüktetést érzékeltetjük",
    "f12b1d77": "Hipp, hopp, haja hopp… Sári néni utazik… Az egyenletes lüktetést többféleképpen érzékeltetjük",
    "b546bb5f": "Kerekecske… Kert alatt… Hová mégy, te kis… Az egyenletes lüktetést mondókán érzékeltetjük",
    "04e8d457": "Kinyílt a rózsa… Hová mégy, te kis… Kiemeljük a dalok és a mondókák ritmusát",
    "9cbf16bd": "Hóember, hóember… Egyszerű dallamfordulatokat énekelünk vissza",
    "b40f2634": "Erre csörög… Az egyenletes lüktetést játékos mozdulatokkal érzékeltetjük",
    "11e24e0c": "Ciróka, maróka… Csipp, csepp… Én kis kertet kerteltem… A magas és a mély hangot beszéddel érzékeltetjük",
    "46f8b60b": "Lóg a lába… Sétálunk… Kiemeljük a dalok és a mondókák ritmusát",
    "e54ad8dd": "Áspis kerekes… Esik az eső… Én kis kertet kerteltem… A magas és a mély hangot mondókán érzékeltetjük",
    "94f01cf6": "Rózsa szirma… Erzsébet asszony… A dalritmusok különbsége és kapcsolata",
    "219eb530": "Gólya viszi a fiát… A magas és a mély hangot furulyán és dalon érzékeltetjük",
    "6714b7d7": "Fújja szél a… Csicseriborsó… Érzékeltetjük a magas és a mély közti különbséget",
    "2b7a0e15": "Hold, hold… Csicseriborsó… Érzékeltetjük a magas és a mély közti különbséget",
    "cd1b9795": "A hajnali harangszónak… Négy vándor jár… Érzékeltetjük a magas és a mély közti különbséget",
    "71fc5027": "Csipp, csepp, egy csepp… Zsipp, zsupp, kenderzsupp… Én kis kertet kerteltem… Hallásfejlesztés: honnan szól a csengő?",
    "777917be": "Mit mos, mit mos… Én kis kertet kerteltem… Úszik a kácsa… Széken ülve, helyben topogunk az egyenletes lüktetésre",

    # ===================== KÜLSŐ VILÁG =====================
    "7b6bb488": "Mit jelent a tél kezdete és az advent, és mik a közelgő ünnep jelképei?",
    "1bb95cd5": "Közösen feldíszítjük a csoportszobát, és megteremtjük az ünnep hangulatát",
    "69f76d61": "Miért jó együtt lenni a családdal, és mit ér az egymásért végzett munka?",
    "6f4b57af": "Digitális eszközzel ismerkedünk az állatokkal és a madarakkal",
    "d6af3d85": "Könyveket és képeket nézegetünk az állatokról és a költöző madarakról",
    "d1cc2923": "Állatkerti kiránduláson ismerkedünk a különféle állatfajokkal",
    "8b04eb14": "Fényképek nézegetése közben bemutatjuk a családunkat",
    "62615423": "Készülődünk anyák napjára, és ráhangolódunk az ünnepre",
    "947dd488": "Köszöntés: hogyan fejezzük ki a szeretetet és az összetartozást?",
    "040a6570": "Kinek van iskolás testvére? Miért járunk iskolába, és mi kerül a táskába?",
    "b7904b5c": "Iskolalátogatás: játékosan ismerkedünk a tanítókkal és az osztálytermekkel",
    "daccb4f4": "Mikor mondjuk, hogy egészségesek vagyunk, és mitől leszünk betegek?",
    "918c6056": "Szétválogatjuk, mi egészséges és mi nem: ételek, italok, tevékenységek",
    "5871daba": "Mit tehetünk magunkért, hogy megőrizzük az egészségünket?",
    "271717bb": "Digitális eszközzel és könyvekkel ismerjük meg a vadon élő állatok külsejét",
    "fb034128": "Digitális eszközzel és könyvekkel ismerjük meg a vadon élő állatok mozgását, életmódját",
    "0f70ec17": "Hogyan hat az időjárás a környezetünkre: az emberre, a növényekre, az állatokra?",
    "53a4db33": "Megfigyeljük, hogyan váltják egymást az évszakok",
    "871e2600": "Farsangi népszokások: közösen kiszebábot készítünk és elégetjük",
    "00ecae9d": "Digitális eszközzel ismerjük meg a medvét és a külső jegyeit",
    "8c85164b": "Digitális eszközzel ismerjük meg a medve mozgását és életmódját",
    "b65ab962": "Február 2., gyertyaszentelő: ismerkedés a népszokással",
    "8a239379": "Kibújik-e a medve a barlangjából? Az időjósló nap",
    "b1e69b92": "Betlehemes műsort dramatizálunk, és bemutatjuk a szülőknek",
    "88eaf4e6": "Beszélgetünk az emberek munkájáról és a foglalkozásokról",
    "165db125": "Munkafolyamatokat követünk nyomon képeken, digitális eszközzel és látogatásokon",
    "9fa800cd": "Földgömb segítségével ismerkedünk a bolygónkkal",
    "f5e02cdc": "Miért fontos védeni a városi és az erdei fákat, növényeket?",
    "ed2b5528": "Felelevenítjük és bővítjük, amit a Földről tanultunk",
    "e56edb27": "Szokások, történetek és versek a gyermeknapról",
    "e44b6f6c": "Plakátot és meghívót készítünk az óvodai gyermeknapra",
    "719784fb": "Gazdasági udvarba látogatunk: szárnyasokat, nyulat és bárányt figyelünk meg a saját környezetükben",
    "5caeb7ed": "Megismerjük a húsvéti hagyományokat és népszokásokat",
    "bb0b652e": "Felelevenítjük a húsvéti hagyományokat, és bővítjük, amit már tudunk róluk",
    "c30cccfa": "Folyamatosan figyelemmel kísérjük, hogyan újul meg a természet",
    "36ffa7f1": "A baromfiudvarban felfedezzük a gazdasági udvar lakóit",
    "156fd367": "Rendezzük és csoportosítjuk a családtagok fényképeit",
    "c278e2ea": "Megnevezzük a családtagokat, és megbeszéljük, mitől vagyunk egy család",
    "54e536f5": "Megfogalmazzuk, mit jelent a családi szeretet és a jeles napok megünneplése",
    "854fa074": "Séta közben megfigyeljük az időjárás változását és az ősz jeleit",
    "1fe35b14": "Az őszi időjárás megfigyelése közben felismerjük az évszak jellemzőit",
    "0e54d1b5": "Megtapasztaljuk, hogyan függ össze az időjárás és az öltözködés",
    "91dbdb1d": "Képekről felismerjük a közlekedési eszközöket és a járműveket",
    "c86cc590": "Kiránduláson gyakoroljuk a gyalogos és a tömegközlekedést, és tudatosítjuk a szabályokat",
    "4976c816": "Gyakoroljuk a gyalogos, a kerékpáros és a tömegközlekedést",
    "fabafe64": "Kerékpáros kiránduláson is tudatosítjuk és megszilárdítjuk a szabályokat",
    "6304dd55": "Hogyan készülnek a madarak a télre, és hogyan gondoskodunk az itt maradókról?",
    "65d0465d": "Ismerkedünk a lakóhelyünkkel, majd egyre távolabbi környezetünkkel",
    "54719a8b": "Ismerkedünk a nemzeti jelképeinkkel: zászló, kokárda, korona, a település és az ország címere",
    "cd13c31b": "Megismerjük az 1848–49-es forradalom történetét",
    "71655c05": "Hogyan készül a méz, milyen fajtái vannak, mi kell hozzá, és miért kell védeni a méheket?",
    "214d064f": "Piaci látogatás: ismerkedünk a vásározás hagyományával",
    "80e5cdca": "Megismerjük a vásári szokásokat, és vásárfiát készítünk",
    "9d9ba487": "Beszélgetés a Mikulásról: hol él, kik segítik, mi a dolga?",
    "0988ea1a": "Napszakórát készítünk, és rögzítjük rajta a napi tevékenységeket",
    "b6d0eecd": "Gyümölcsöket figyelünk meg, felismerjük, megízleljük és összehasonlítjuk őket",
    "29992445": "Mire van szükségünk ahhoz, hogy feldolgozzuk a szőlőt?",
    "eaedde50": "Megismerjük a szüretelést, a darálást és a préselést, vagyis a szőlő feldolgozását",
    "b1ef26eb": "Bővítjük a tudásunkat a néphagyományokról és a szokásokról",
    "1537c79a": "Nevezzük meg őket, és ismerkedjünk a tulajdonságaikkal",
    "24f74a09": "Megismerjük, mire használjuk a zöldségeket, hogyan tartósítjuk, és mivel óvják az egészségünket",
    "a2f08758": "Pattogatott kukorica készítése közben ismerkedünk a kukoricával",
    "390014db": "Milyen őszi zöldséget vegyünk a csalamádéhoz?",
    "dffaf196": "Kukoricatörés, tök és répa betakarítása egy családi kertben",
    "3339eb8e": "Ismerkedünk az óvodával, a környezetével, a felnőttekkel és a társakkal",
    "b562b316": "A kicsikből középsősök, a középsősökből nagycsoportosok lettek",
    "19b0dc2b": "Naptárszínezés: mennyi időt töltöttünk egymástól távol?",
    "91ce7723": "Élményt adó séta közben beszélgetünk a tavaszi időjárás jellemzőiről",
    "90d561a4": "Megfogalmazzuk az évszakhoz fűződő személyes élményeinket és érzéseinket",
    "2daad81d": "Tapasztalatszerző sétán megfigyeljük a növény- és állatvilág változásait",
    "3e81219f": "A tavaszi zöldségek és gyümölcsök színe, formája és íze",
    "df81d654": "Megismerjük a tavaszi zöldségeket, gyümölcsöket és virágokat",
    "8ebc9faa": "Melyik részüket esszük meg a zöldségeknek és a gyümölcsöknek?",
    "ce382482": "A tél örömei: szánkózunk, hógolyózunk, hóembert építünk",
    "b735f721": "Összefüggést keresünk a téli időjárás és az öltözködésünk között",
    "2936af7d": "Megfigyeljük a téli természeti jelenségeket, és megbeszéljük a tapasztalatainkat",
    "2a622531": "Hogyan hat a téli időjárás az emberre és az egészségünkre?",
    "596c10d0": "Megnevezzük az érzékszerveinket, és megismerjük a főbb testrészeinket",
    "aeb5ccdb": "Megismerjük és felismerjük az érzékszerveket és a testrészeket",
    "77665507": "Megismerjük az érzékszervek működését, és azonosítjuk a testrészeket",
    "24a97408": "Tudatosítjuk a páros testrészeinket és a külső jellemzőinket",
    "d7c788cf": "Megismerjük az emberi test felépítését, a fontosabb belső szerveket és a működésüket",
    "48a46b65": "Hangokat, színeket, ízeket és illatokat különítünk el, és kötjük a megfelelő érzékszervhez",
    "1faf5b35": "Beszélgetünk az újévi hagyományokról, és újévi köszöntőt mondunk",
    "a8b09a0d": "Újév ágát és köszöntőkártyát készítünk a szülőkkel",
    "e569374e": "Egészségügyi teendők: fogmosás étkezés után is, rendszeres tisztálkodás",
    "62e97ebb": "Megóvjuk a Föld értékeit, és tudatosítjuk, milyen fontos a tiszta ivóvíz",

    # ===================== MATEMATIKA =====================
    "c55af2c6": "Több, kevesebb, ugyanannyi becsléssel és összeméréssel: az adventi naptár napjai, a koszorú gyertyái",
    "a4d5339b": "A karácsonyi díszeken azonos formákat keresünk és párosítunk",
    "0cd34237": "Halmazképzés: szétválogatjuk az állatokat háziállatra, vadállatra, madárra",
    "5dea72b2": "Számlálás a csoport műanyag állataival és állatképeivel",
    "98c87d71": "Állatos társasjátékot készítünk: számlálunk, és mennyiség szerint hasonlítjuk össze a halmazokat",
    "36c721f1": "Hány főből áll a család? Állapítsuk meg a számosságot",
    "67fe8737": "Melyik családtag a kisebb, melyik a nagyobb, és ki ugyanakkora?",
    "0a55c82e": "Megszámoljuk az anyák napi ajándékokat, és műveleteket végzünk velük",
    "43b20280": "Tárgyak képeit válogatjuk szét adott tulajdonság szerint: kell-e ez az iskolába?",
    "7f7aed14": "Tárgyakat rendezünk sorba a saját elgondolásunk szerint",
    "8a241103": "Számokat rendelünk mennyiségekhez: színes ceruzák, padok",
    "ad714271": "Számolás tízig ujjakkal, képekkel és tárgyakkal",
    "f1e52887": "Társasjáték az erdő állataival, pörgethető táblán",
    "687871fd": "Számlálás az általunk készített állatokkal",
    "675b45e8": "Állatok háza: annyi állat költözhet be, amennyit dobtunk",
    "8c41f3ce": "Ok-okozati összefüggések, valamint az évszakok és a hónapok számlálása",
    "aaa22d06": "A farsangi díszeken színt és formát azonosítunk",
    "9f9c918d": "A farsangi girlandon a hosszabb és a rövidebb viszonyát keressük",
    "a0785676": "Árnyképeket azonosítunk az eredetivel: bohóc, kiszebáb, kalap",
    "7b6dde5a": "A medvéket csoportosítjuk, halmazt alkotunk szín és nagyság szerint",
    "a58ce0ef": "A medvefajok képeit csoportosítjuk, majd összehasonlítjuk a darabszámukat",
    "83fd31cb": "A medvék árnyképét azonosítjuk az eredeti képpel",
    "eaf66167": "Halmazokat alkotunk, és az elkészült díszek jellemzői szerint változtatjuk a tulajdonságaikat",
    "b4fdd125": "Gyertyákból halmazt alkotunk, majd változtatunk rajta: hozzáteszünk, elveszünk, ugyanannyivá tesszük",
    "acc37565": "Tárgyakat és személyeket válogatunk, és foglalkozásokhoz rendeljük őket",
    "db898eda": "A foglalkozások árnyképét azonosítjuk az eredetivel",
    "e0be3389": "Halmazképzést gyakorlunk gyűjtőfogalmakkal: foglalkozások, szerszámok",
    "b65224a9": "Melyik fa, növény vagy állat a legkisebb a valóságban?",
    "42f97f46": "A földgömbön érzékeltetjük a többet, a kevesebbet és az ugyanannyit: víz és szárazföld",
    "f56ff209": "Ok-okozati összefüggéseket ismerünk fel a környezetvédelemben",
    "561950f2": "A csoporttársainkon végzünk nehezebb és könnyebb összehasonlításokat",
    "db6bee46": "A gyerekek külső jegyei alapján azonosságot és különbséget ismerünk fel",
    "8cf3f924": "A plakát és a meghívó készítése közben gyakoroljuk a jobbot és a balt",
    "656a9d75": "Összehasonlítjuk a tojások méretét, és méret szerint sorba rendezzük őket",
    "0c9f9d8c": "Tojásgyűjtő verseny és tojáskeresés: számosság, csoportosítás, becslés, mérés, összehasonlítás",
    "03729dba": "A családtagok rendezése közben sorszámneveket használunk",
    "cbece2ee": "Kinek a legnagyobb a családja? Sorszámnevek és sorozatok",
    "3e4ab3c0": "Öltözködés közben ismerjük fel a ruhákon a rövidebbet és a hosszabbat, a keskenyebbet és a szélesebbet",
    "c2aa7b71": "Számlálással állapítjuk meg, hány ruhadarab van",
    "c7736d24": "Téri tájékozódás: jobbra, balra, előre, hátra",
    "236bfd29": "Közlekedés közben fedezzük fel a térbeli viszonyokat",
    "92aabc65": "Madarakat párosítunk többféle szempont szerint: faj, szín, élőhely",
    "fc0e5629": "Madárképek kiegészítésével ismerjük fel a rész és az egész viszonyát",
    "36dee71b": "Várépítés közben ismerkedünk a geometriai testekkel és formákkal",
    "03549206": "Ki lakik közelebb és ki távolabb az óvodától, a játszótértől, a bolttól?",
    "85f10489": "Megfigyelünk, összehasonlítunk, és felismerjük az azonosságot meg a különbséget",
    "102919a6": "Hány liba szaladgált a baromfiudvarban? Számláljuk meg",
    "4fdecef5": "A baromfiudvar állatait méret szerint sorba rendezzük",
    "9b2d10a8": "A hagyomány szerint hány liba fért a libaólba?",
    "66a37174": "Sorok hosszát hasonlítjuk össze becsléssel és méréssel",
    "0cb39741": "Számlálás adott szempont szerint: mézfajták, méhecskék, kaptárak",
    "bd22f998": "A méhészetben készült képekkel fejlesztjük a rész-egész észlelést",
    "23987854": "A piacon az árusok portékájának mennyiségével tudatosítjuk a több és a kevesebb fogalmát",
    "6e5c88bd": "A piacon az árusok portékáján, számlálással fejlesztjük a mennyiségi különbségek észlelését",
    "f0d4ea0f": "Vásárfia készítése és vásározás közben pénzt és portékát számlálunk",
    "ea936304": "Térbeli viszonyokat gyakorlunk: hol van a kémény?",
    "30dd91ec": "Logikai műveletek gyakorlása: állítás és tagadás",
    "bd835a0c": "A hét napjait gyakoroljuk és soroljuk",
    "3d3e6bed": "Mit mikor csinálunk a nap folyamán?",
    "fc186800": "A gyümölcsök darabolásával érzékeltetjük a rész és az egész viszonyát",
    "4b9b4629": "Szőlőszemekkel gyakoroljuk a számlálást és a leképezést",
    "03d0bc83": "Mérés és összehasonlítás fürtökkel, szőlőszemekkel, pohárba és kancsóba töltött musttal, becsléssel",
    "682cf57f": "Halmazképzés: leveleket és terméseket válogatunk forma és nagyság szerint",
    "de192486": "Megbecsüljük a kiránduláson gyűjtött termést: gesztenyét, diót, makkot",
    "dd1fb380": "Terméseket számlálunk párosítással, és kirakjuk a több, a kevesebb és az ugyanannyi jelét",
    "2b1f2f84": "A zöldségeket szín és forma szerint csoportosítjuk",
    "1329af4e": "Megmérjük a zöldségek és a gyümölcsök hosszát: hosszabb, rövidebb, ugyanolyan hosszú",
    "f9ff5080": "Őszi gyümölcsökön és zöldségeken gyakoroljuk az összehasonlítást, a gyerekek által kitalált szempontok szerint",
    "ce357508": "Ismerkedünk a zöldségek formájával, és szín szerint csoportosítjuk őket",
    "cf6a5fbf": "Megvásároljuk a megbeszélt darabszámú zöldséget",
    "ceb2d387": "Hosszúságmérés többféle egységgel: hány répa hosszú a kukorica szára?",
    "9e8adac8": "Összehasonlítjuk a méreteket: melyik a leghosszabb és melyik a legrövidebb zöldség a kertben?",
    "f0948237": "Testmagasság és tömeg: becslés, mérés, összehasonlítás súlyokkal",
    "8e1066a1": "Halmazokat alkotunk, és több szempontból hasonlítjuk össze az elemeiket",
    "3a007006": "Kavicsokat hasonlítunk össze forma és nagyság szerint",
    "84673e50": "Súlyt becslünk, majd mérleggel ellenőrizzük: kavics, homok",
    "60111872": "Gyakoroljuk a számlálást: számoljunk el, ameddig tudunk, például a fák virágait vagy a hangyákat",
    "cf60137b": "Összehasonlítjuk a zöldségek és a gyümölcsök méretét",
    "c674ccdb": "A zöldségeken, gyümölcsökön és virágokon ellentétet, azonosságot és különbséget fedezünk fel",
    "2e8f48d8": "Ellentétpárokat keresünk a zöldségeken, gyümölcsökön, virágokon: vastag és vékony, hosszú és rövid, és megállapítjuk a számosságot",
    "04b08a6b": "Halmazt alkotunk az évszakra jellemző képekből, és megnevezzük, amit látunk",
    "a37660f6": "Sorokat alkotunk többféleképpen a télre jellemző tárgyak képeiből",
    "4bf245d7": "Két halmazba gyűjtött ruha tulajdonságait tárjuk fel: rövid és hosszú, hideg és meleg, vastag és vékony",
    "4a6c5940": "Párosítás testrészekkel és ruhadarabokkal",
    "b89b3ae9": "Testrészek és ruhadarabok párosításával ismerjük meg a pár fogalmát",
    "22560248": "Számokat mutatunk az ujjunkon, képek segítségével",
    "10226d78": "Kesztyűt, sálat és cipőt válogatunk többféle szempont szerint: melyik az enyém?",
    "7d9cf5d0": "Halmazt alkotunk az újév jelképeiből, valamint az évszakra és a napszakra jellemző képekből",
    "afadd916": "Azonosság, különbség, több és kevesebb a csapból és a közeli tóból vett minta alapján",

    # ===================== MOZGÁS =====================
    "e1ae0fa9": "Egyensúlyozó járás a padon, a fölötte kifeszített zsinór átlépésével",
    "4c2cfefa": "Futás többféle irányba, jelre irányt váltunk",
    "fd1e7254": "Egyensúlyozó járás, szökdelés és ugrás a széksoron",
    "e3056e4c": "Mászás előre és hátra, sávokban, babzsákot csúsztatva",
    "94a6465d": "Mászás oda-vissza a sávokban, babzsákot tolva magunk előtt",
    "043f5bf9": "Csúszás, mászás és támaszugrás a padon, babzsákkal",
    "cb093757": "Hógolyózás, csúszkálás a jégen, szánkózás, nyomkeresés a hóban",
    "13bdbc35": "Gurulás a hossztengely körül, párban, rézsútos szeren",
    "d53a0a81": "Labdát adunk tovább a társnak, miközben a padpáron haladunk",
    "3c00e6ab": "Hason kúszás a kifeszített zsinór alatt, ügyességi versenyként",
    "01917c5a": "Négykézláb járás, egyensúlyozás, átbújás a szer alatt",
    "6f0de602": "Lajhárfüggés: függés, lengés, majd leugrás",
    "dacac645": "Soros függésben haladunk tovább, és összeérintjük a testrészeinket",
    "a4339975": "Soros függésben kezet fogunk, és összeérintjük a testrészeinket",
    "8953e10d": "Mászás babzsákkal, különböző alakzatokat követve",
    "91938bf3": "Járás, futás és mászás közben babzsákot tolunk bottal, változó alakzatokban",
    "8988aa46": "Szivacslabdát gurítunk kézzel és lábbal, mászás közben, a padok között",
    "21a8c7f6": "Léglabdát gurítunk kézzel és lábbal, mászás közben, a padok között",
    "711aea4b": "Léglabdát gurítunk a vonalak között és a vonalon, majd leütéssel a társnak",
    "cb49cb3f": "Versenyvonatozás, figyelemfejlesztő versenyjáték",
    "242db215": "Versenyvonatozás: figyelemfejlesztő versenyjáték csapatokban",
    "2cc44bc9": "Egyensúlyozó gyakorlatok a homokozó szélén és a padon",
    "368264ba": "Egyensúlyozó gyakorlatok rézsútos és felfordított padon",
    "36fac9f2": "Csúszás, kúszás és mászás, közben babzsákot adunk tovább",
    "893798f9": "Ismerkedés az óvoda udvari és tornaszobai játékaival",
    "62bced16": "Egyensúlyozó járás a padon szerpentinnel, előre és hátra, a végén mélyugrás",
    "d5670778": "Egyensúlyozó járás a padon szerpentinnel, előre és hátra",
    "835bea34": "Átugrunk a kifeszített kötelekből épített akadályokon",
    "c8f80197": "Futás, kúszás és csúszás közben bújunk és akadályt lépünk át",
    "d43fb03e": "Futás, kúszás és csúszás közben kötél fölött lépünk át",
    "6574ed2f": "Labdagurítás és labdavezetés járás, majd futás közben",
    "1691f3e8": "Tűz, víz, repülő: játék jellegű főgyakorlat a mozgásos képességek fejlesztésére",

    # ===================== RAJZOLÁS, FESTÉS =====================
    "0c313119": "Karácsonyfadísz: szívet, fenyőfát, házikót szaggatunk só-liszt gyurmából",
    "11809a9b": "Karácsonyfadísz: girlandot fűzünk színes papírcsíkokból",
    "dfe20f1a": "Kutya- és cicabáb papírzacskóból, előre kivágott formák ragasztásával",
    "8141e046": "Nyuszi- és bocibáb papírzacskóból, a fejformát maguk vágják ki",
    "ca85aac0": "Róka-, maci- és lovacskabáb papírzacskóból, önálló vágással és ragasztással",
    "ab60ceac": "Anyák napi képeslap kéz- és ujjlenyomattal",
    "ac4b8e0c": "Anyák napi ajándék: orgonavirág krepp-papír-golyókból ragasztva",
    "3a33a41b": "Anyák napi ajándék: ékszertartó levegőn száradó gyurmából",
    "1b6c36ef": "Téli kép csomagolópapírra, marokecsettel festve",
    "b57e0608": "Sapka és sál ragasztása ritmikus csíkokból, színes papírból",
    "9d779172": "Ajándék az elsősöknek: könyvjelzőt szövünk",
    "5eafac41": "Zöldségeket és gyümölcsöket formázunk színes só-liszt gyurmából",
    "dccebbae": "Zöldség- és gyümölcsformák színes só-liszt gyurmából",
    "47b5cef5": "Róka- és nyuszibáb papírzacskóból, színes papír ragasztásával",
    "330f61ea": "Évszakfa színes gombok ragasztásával",
    "05ead59c": "Évszakfa festett tésztából",
    "db6cfae6": "Álarcot készítünk és díszítünk krepp-papír-golyókkal",
    "30302718": "Csákót díszítünk színes formákkal: kör, négyzet, háromszög",
    "a2b92666": "Cica-, kutya- és bociálarc festéssel vagy zsírkrétával",
    "07b09d65": "Medvefejdísz az előre elkészített részek összeragasztásával",
    "0a7f5ff1": "Medvefejdísz, a fejformát maguk vágják ki",
    "e99cc99e": "Medvefejdísz: a részeket maguk rajzolják, vágják és ragasztják",
    "45a19439": "Csillag és fenyőfadísz spatulából összeragasztva, majd csillámporral díszítve",
    "a3ef4c7c": "Filcből kivágott csillagot, szívet, fenyőfát díszítünk gombbal és flitterrel",
    "173d6914": "Gyakoroljuk és elmélyítjük a nyomatkészítést",
    "a15ee90d": "Pólót és szoknyát mintázunk ujjlenyomattal és dugónyomdával",
    "5d2a01d0": "Fát készítünk kézlenyomattal, csomagolópapírra",
    "5b5208a8": "Bowlingbábut készítünk műanyag henger befestésével",
    "9edc5299": "Közös munkával tavaszi képet festünk lepedőre",
    "9fe3313a": "Tojásformát díszítünk színes só-liszt gyurmával",
    "2417cd41": "Tojásformát díszítünk krepp-papír-golyókkal",
    "f8b84688": "Karácsonyi ajándék: képeslapot készítünk",
    "75349a90": "Karácsonyi ajándék: mécsestartó befőttesüvegből",
    "c1d9e595": "Karácsonyi ajándék: angyalka karácsonyfadísz",
    "4f8087d6": "A kivágott sál- és sapkaformát marokecsettel festjük be",
    "e9853038": "Sapka- és sálformát vágunk ki, majd anyagokkal díszítjük",
    "9e684fe5": "Busz és autó WC-papír-gurigából, színes papírral",
    "9b17b335": "Autó gyógyszeres dobozból, színes papírral",
    "1e403613": "Madárka ujjbáb, a szárnyakat maguk vágják ki",
    "1eb5d018": "Madáretető vegyes technikával: kartonból az etető, origami madárkák, színes papírból az etetőtál, végül magvakat szórunk bele",
    "14a6c5f2": "Magyar zászlót mintázunk parafa dugónyomdával",
    "60552f82": "Szívet ragasztunk piros-fehér-zöld krepp-papír-golyókból",
    "86fd15e1": "Az előre kivágott libaformát marokecsettel festjük, és libatollat ragasztunk rá",
    "5c58ecc6": "Libaformát rakunk ki sodort krepp-papírból",
    "573a4312": "Libafejdísz önálló vágással és ragasztással",
    "9b029f17": "Töröm, töröm… Bevásárlókosarat készítünk kartonból",
    "a5fffde2": "Mikulás-formát festünk, a szakállát vattával mintázzuk",
    "fb99c1d4": "Mikulás-síkbáb önálló vágással és ragasztással",
    "771b64cd": "Napszakóra: körformát vágunk ki, és ráragasztjuk a napi tevékenységeket",
    "bf686b70": "Napszakóra, a napi tevékenységeket magunk rajzoljuk rá",
    "307cd08e": "Szőlőforma papírcsíkok összeragasztásából",
    "5b528bbc": "A kivágott zöldségformát mozaikozással díszítjük",
    "b78bb033": "Formát díszítünk pattogatott kukoricával",
    "081720b4": "Egyszerű állatok só-liszt gyurmából: kígyó, csiga, sün",
    "d9d7d5c8": "Nyári élményrajz szabadon választott technikával",
    "1100bd4f": "Pillangó- és katica-ujjbáb kartonból, ragasztással",
    "ed29862a": "Pillangó- és katica-síkbáb vágással és ragasztással",
    "2c01b6dd": "Zöldségestál széttépett színes papírokból",
    "37aad0d2": "Virág fakanálbáb festéssel és színes karton ragasztásával",
    "cfd275d3": "Testrészeket ragasztunk össze előre kivágott formákból",
    "85cb9754": "Az érzékszerveket rajzoljuk rá a kivágott arcformára",
    "a67e26f9": "Önarckép szabadon választott technikával",
    "986b0b9d": "Saját arcunkat formázzuk színes só-liszt gyurmából",
    "8977cbdb": "Saját magunkat formázzuk meg színes só-liszt gyurmából",
    "9a2bf77a": "Kesztyűt és cipőt mintázunk vattával, valamint előre kivágott kör és négyzet alakú színes papírral",
    "b88ac0ef": "Karácsonyi élményrajz szabadon választott technikával",
}
