# -*- coding: utf-8 -*-
"""
A „Tappancs” heti tervezet-gyűjteményből átvett irodalom (GENERÁLT FÁJL).

Forrás: a kiadvány 36 hetének Verselés, mesélés és Ének, zene rovata,
korcsoportonként. A kinyerést a `tools/tappancs_kinyeres.py`, a modul
előállítását a `tools/tappancs_korpusz.py` végzi — kézzel ne szerkeszd,
mert a következő generálásnál elveszik.
"""

from .base import _t

_t("advent", [
    ("anyanyelvi", None, "Csendjáték", "123", "Leülünk vagy lefekszünk a szőnyegre, és egy ideig csak a környező hangokra figyelünk. Az ünnep csendjére hangol."),
    ("anyanyelvi", None, "Felakasztott hópihék (vattapamacs) fújása", "123", "Zsinórra akasztott vattapamacsot fújunk, hogy meglendüljön."),
    ("anyanyelvi", None, "Hópihe fújása", "123", "Felakasztott vattapamacsot fújunk. A nagyobbaknál másféle könnyű anyagot is felakaszthatunk, és összevetjük, melyiket könnyebb megmozdítani."),
    ("dal", None, "Ciróka, maróka", "12", ""),
    ("dal", None, "Fehér karácsony", "2", ""),
    ("dal", None, "Szálljatok le", "3", ""),
    ("dal", None, "Tüzet viszek", "3", ""),
    ("dal", None, "Ég a gyertya ég", "1", ""),
    ("vers", "Móra Ferenc", "A didergő király", "2", ""),
    ("mese", "Tóthárpád Ferenc", "A negyedik gyertyaláng", "3", ""),
    ("mese", "Jakob és Wilhelm Grimm", "A suszter manói", "2", ""),
    ("mese", "Mentovics Éva", "Mióta van csillag a karácsonyfák csúcsán?", "3", ""),
    ("mondoka", None, "Advent (Magyar népköltés)", "3", ""),
    ("nepmese", None, "A kesztyű", "1", ""),
    ("nepmese", None, "Miklós püspök legendája", "3", ""),
    ("nepmese", None, "Visszajött a répa", "1", ""),
    ("vers", "Donászy Magda", "Karácsony", "1", ""),
    ("vers", "Pálfalvi Nándor", "Karácsony", "2", ""),
    ("vers", "Zelk Zoltán", "Téli fák", "2", ""),
])

_t("allatok_vilagnapja", [
    ("dal", None, "Cicukám, kelj fel", "1", ""),
    ("dal", None, "Cicuska, macuska", "3", ""),
    ("dal", None, "Egy, begy, tyúkbegy", "2", ""),
    ("dal", None, "Fáj a kutyámnak a lába", "1", ""),
    ("dal", None, "Kis, kis kígyó", "2", ""),
    ("dal", None, "Sánta róka", "3", ""),
    ("mese", "Kolozsvári Grandpierre Emil", "A két kicsi bocs meg a róka", "1", ""),
    ("mese", "Móricz Zsigmond", "Iciripiciri", "1", ""),
    ("mese", "Zelk Zoltán", "Mese az éhes kisegérről", "3", ""),
    ("mondoka", None, "Verses mesék", "2", ""),
    ("nepmese", None, "A róka meg a farkas aratni megy", "3", ""),
    ("nepmese", None, "Furulyás Palkó", "2", ""),
    ("vers", "Bartos Erika", "Csigabiga", "1", ""),
    ("vers", "Szabó Lőrinc", "Falusi hangverseny", "3", ""),
    ("vers", "Weöres Sándor", "Kutyatár", "2", ""),
    ("vers", "Kányádi Sándor", "Róka-mondóka", "2", ""),
    ("vers", "Csukás István", "Sün Balázs", "2", ""),
    ("vers", "Gazdag Erzsi", "Tarka cica, fehér cica", "1", ""),
    ("vers", "Fazekas Anna", "Öreg néne őzikéje", "2", ""),
])

_t("anyak_napja_csalad", [
    ("anyanyelvi", None, "Dobjunk puszit / Fújjunk szívecskét", "1", ""),
    ("anyanyelvi", None, "Karmester", "23", "Kijelölünk egy karmestert, aki kitalál és bemutat egy mozdulatsort, majd választ valakit, aki utánozza."),
    ("dal", None, "Eresz alól", "1", ""),
    ("dal", None, "Ispiláng, ispiláng", "1", ""),
    ("dal", None, "Orgona ága", "1", ""),
    ("dal", None, "Rozmaringos ablakomba", "1", ""),
    ("dal", None, "Édesanyám szeret engem", "1", ""),
    ("dal", None, "Én kicsike vagyok", "1", ""),
    ("dal", None, "Ó, ha cinke volnék", "1", ""),
    ("dal", None, "Örömünnep ez a nap", "1", ""),
    ("dal", None, "Ültem ringó", "1", ""),
    ("mese", "Petrolay Margit", "A legszebb vasárnap", "3", ""),
    ("mese", "Fésűs Éva", "Májusi mese", "3", ""),
    ("nepmese", None, "A farkas és a hét kecskegida", "1", ""),
    ("vers", "Mentovics Éva", "A legdrágább anyukának", "3", ""),
    ("vers", "Tordon Ákos", "Anyáknapi mondóka", "1", ""),
    ("vers", "Lukács Angéla", "Csak egy van", "2", ""),
    ("vers", "Kiss Jenő", "Meghajtom magam most", "2", ""),
    ("vers", "Osvát Erzsébet", "Meséltél és meséltél", "2", ""),
    ("vers", "Ágh István", "Virágosat álmodtam", "1", ""),
    ("vers", None, "Édesanyám, neked adunk minden évben egy napot", "3", ""),
])

_t("balazs_nap_iskola", [
    ("anyanyelvi", None, "Robotnyelv", "123", "Szótagolva, robotosan beszélünk. Előbb két szótagú szavakkal és nevekkel, később hosszabbakkal."),
    ("anyanyelvi", None, "Robotnyelv játék", "23", ""),
    ("dal", None, "Erzsébet asszony", "23", ""),
    ("dal", None, "Ilyen cica mellett", "1", ""),
    ("dal", None, "Kicsi kocsi, három csacsi", "3", ""),
    ("dal", None, "Sárga rózsa, vadvirág", "12", ""),
    ("mese", "Szabó Zsolt", "A rénszarvas barlangja", "1", ""),
    ("mese", "Fésűs Éva", "Bundavásár", "2", ""),
    ("mese", "Szabó Zsolt", "Hull a hó", "1", ""),
    ("mondoka", None, "Kismanó óvodába indul", "3", ""),
    ("mondoka", None, "Kisnyuszi suliba megy", "3", ""),
    ("vers", "Fazekas Lajos", "Aludj, fácska", "2", ""),
    ("vers", "Szűcs Imre", "Február", "1", ""),
    ("vers", "Weöres Sándor", "Olvadás", "1", ""),
    ("vers", "Gyurcsó István", "Téli tó", "1", ""),
    ("vers", "Gyárfás Endre", "Írogató", "3", ""),
    ("vers", "Kányádi Sándor", "Ábécé-sorakozó", "3", ""),
])

_t("egeszseges_eletmod", [
    ("anyanyelvi", None, "Befejezetlen mondat", "123", "Elkezdünk egy mondatot az egészséges életmódról, a gyerekek megismétlik, majd a maguk szavaival befejezik."),
    ("anyanyelvi", None, "Hangutánzós", "123", "A kisebbek állatok és járművek hangját utánozzák. A nagyobbak egymást: megfigyelik, milyen hangerővel és hangsúllyal beszél a társuk, és azt próbálják visszaadni."),
    ("dal", None, "Kicsi vagyok", "1", ""),
    ("dal", None, "Most viszik", "2", ""),
    ("dal", None, "Pörcös pogácsa", "1", ""),
    ("dal", None, "Sírjunk, ríjunk", "2", ""),
    ("dal", None, "Süssünk", "3", ""),
    ("dal", None, "Éliás, Tóbiás", "3", ""),
    ("mese", None, "Makk Marci sorozat: Fognyűvő manócska", "2", ""),
    ("mondoka", None, "Fáj a kutyámnak a lába", "1", ""),
    ("nepmese", None, "Két kis fog Tündérországban", "1", ""),
    ("vers", "Szalai Borbála", "A makk", "3", ""),
    ("vers", "Tamkó Sirató Károly", "Szembeszél", "2", ""),
])

_t("erdo_allatai", [
    ("anyanyelvi", None, "Melyik állat hangját hallod?", "1", "Ismert állatok hangfelvételét hallgatjuk meg, felismerjük és utánozzuk őket."),
    ("anyanyelvi", None, "Találós kérdések az állatokról", "23", "Találós kérdések vadon élő és háziállatokról."),
    ("dal", None, "Benn a bárány", "23", ""),
    ("dal", None, "Egy kis malac", "1", ""),
    ("dal", None, "Hopp, mókuska", "1", ""),
    ("mese", "Móra Ferenc", "Csókai Csóka", "1", ""),
    ("nepmese", None, "A nyúl meg a sün", "2", ""),
    ("nepmese", None, "A róka meg a daru", "3", ""),
    ("vers", "Kerner Tibor", "Kopogó", "3", ""),
    ("vers", "Szalai Borbála", "Sündisznók", "1", ""),
    ("vers", "Székely Dezső", "Téli kertben", "3", ""),
    ("vers", "Fazekas Lajos", "Vadetető", "3", ""),
    ("vers", "Gazdag Erzsi", "Vadnyulak", "2", ""),
    ("vers", "Kányádi Sándor", "Veréb", "1", ""),
])

_t("evszakok_korforgas", [
    ("anyanyelvi", None, "Liccs-loccs, megjött a kishajó", "123", ""),
    ("dal", None, "Adjon isten", "12", ""),
    ("dal", None, "Kicsi csupor", "1", ""),
    ("dal", None, "Négy vándor jár", "2", ""),
    ("dal", None, "Tüzet viszek", "1", ""),
    ("dal", None, "Zsipp-zsupp", "1", ""),
    ("mese", "Zelk Zoltán", "Négy vándor", "3", ""),
    ("mondoka", None, "Hónap-mondóka (magyar népköltés)", "3", ""),
    ("mondoka", None, "Január elöl jár", "3", ""),
    ("mondoka", None, "Jégen járó január", "3", ""),
    ("mondoka", None, "Jön a tavasz, virágot hoz", "1", ""),
    ("nepmese", None, "A hóember orra", "1", ""),
    ("nepmese", None, "A medve a róka meg a bödön vaj", "3", ""),
    ("mese", "Jakob és Wilhelm Grimm", "Holle anyó", "2", ""),
    ("nepmese", None, "Nyuszigyermekek és az első hó", "1", ""),
    ("vers", "Tóth Éva", "Hónapok", "3", ""),
    ("vers", "Csanádi Imre", "Négy testvér", "2", ""),
    ("vers", "Fésűs Éva", "Évszakok", "3", ""),
])

_t("farsang", [
    ("anyanyelvi", None, "Lufifújó verseny", "123", "Ki tudja hamarabb felfújni a lufit? Utána filctollal arcot is rajzolhatunk neki."),
    ("dal", None, "Cini, cini", "1", ""),
    ("dal", None, "Csiteri, csütöri", "1", ""),
    ("dal", "Gazdag Erzsi", "Itt a farsang, áll a bál", "1", ""),
    ("dal", None, "Kőketánc, kőketánc", "1", ""),
    ("dal", None, "Vékony vászon", "1", ""),
    ("mese", "Zelk Zoltán", "Erdei mulatság", "2", ""),
    ("mese", "Bartos Erika", "Jelmezbál", "1", ""),
    ("mese", "Fésűs Éva", "Pöttömke hóember lesz", "3", ""),
    ("vers", "Verseghy Erzsébet", "Bál a konyhában", "3", ""),
    ("vers", "Sarkady Sándor", "Farsang", "3", ""),
    ("vers", "Drégely László", "Farsangi bál", "2", ""),
    ("vers", "Csoóri Sándor", "Farsangnapi kutyabál", "2", ""),
    ("vers", "Tarbay Ede", "Félnótás nóta", "3", ""),
    ("vers", "Gazdag Erzsi", "Itt a farsang", "1", ""),
    ("vers", "Tamkó Sirató Károly", "Mondjam még?", "3", ""),
    ("vers", "Weöres Sándor", "Pletykázó asszonyok", "2", ""),
    ("vers", "Czeglédi Gabriella", "Áll a bál", "1", ""),
])

_t("feny_arnyek_mackok", [
    ("anyanyelvi", None, "Igaz-hamis játék", "1", ""),
    ("anyanyelvi", None, "Ki vagyok én?", "23", "Páros játék állatos fejdísszel. A gyerek a saját fejdíszéről kérdez, a párja csak igennel vagy nemmel felelhet, amíg ki nem találja, milyen állat lett."),
    ("dal", None, "Brum-brum, Brúnó", "2", ""),
    ("dal", None, "Dirmeg, dörmög", "1", ""),
    ("dal", None, "Mackó brummog", "1", ""),
    ("dal", None, "Mackó, mackó", "12", ""),
    ("mese", "Ivan Krilov", "Miért alszik a medve télen?", "2", ""),
    ("mese", "Orosvai Mária", "Téli álom", "3", ""),
    ("mondoka", None, "Bújj, bújj, medve", "1", ""),
    ("mondoka", None, "Dirmeg, dörmög a medve", "1", ""),
    ("nepmese", None, "A naplopó medve", "1", ""),
    ("vers", "Weöres Sándor", "A medve töprengése", "3", ""),
    ("vers", "Csukás István", "Mackómese", "2", ""),
    ("vers", "Osvát Erzsébet", "Minek a medvének bunda", "2", ""),
])

_t("fenyofa_diszek", [
    ("anyanyelvi", None, "Milyen hangot hallasz?", "1", ""),
    ("anyanyelvi", None, "Varázslójáték", "23", "Az óvodapedagógus a varázsló. Egy gyerek kimegy, a bent maradóval közben történik valamilyen varázslat, és a visszatérőnek észre kell vennie, mi változott."),
    ("mese", "Ákossy Eszter", "Korholi titka", "1", ""),
    ("mese", "Linda Jenning", "Pásztorok a hegyen", "2", ""),
    ("nepmese", None, "A kovács lánya", "3", ""),
    ("nepmese", None, "Jézus születése", "3", ""),
    ("vers", "Osvát Erzsébet", "Didergők", "2", ""),
    ("vers", "Sarkadi Sándor", "Hóember", "1", ""),
    ("vers", "Gazdag Erzsi", "Hóember", "1", ""),
    ("vers", "Lendvai Ilona", "Itt a tél", "2", ""),
    ("vers", "Mentovics Éva", "Karácsonyi jókívánság", "3", ""),
])

_t("foglalkozasok", [
    ("anyanyelvi", None, "Mimetikus játék mesterségekről", "1", "Közösen eljátsszuk, hogyan vizsgál a doktor néni, hogyan biciklizik a postás, hogyan rúgja a labdát a focista."),
    ("anyanyelvi", None, "Történet kitalálása képekről", "23", "Egymás mellé tett képekből egy felnőtt napja rajzolódik ki. Közösen történetet találunk ki hozzá."),
    ("dal", None, "Egy kis malac", "1", ""),
    ("dal", None, "Hegedül a kisegér", "1", ""),
    ("dal", None, "Jákobnak volt hat fia", "2", ""),
    ("dal", None, "Megy a kocsi", "2", ""),
    ("dal", None, "Szőjünk fonjunk kendőt", "2", ""),
    ("dal", None, "Szőjünk, fonjunk kendőt", "1", ""),
    ("mese", "Benedek Elek", "A vitéz szabólegény", "3", ""),
    ("mese", "Fehér Klára", "Foglalkozások", "1", ""),
    ("mese", "Petrolay Margit", "Mese a hét mesterségről", "2", ""),
    ("mondoka", None, "Ha valaki vígan él", "2", ""),
    ("vers", "Zelk Zoltán", "A kis kertész", "3", ""),
    ("vers", "Nemes Nagy Ágnes", "Bors néni beszélget az aszfaltozókkal", "3", ""),
    ("vers", "Szép Ernő", "Kaszálnak", "3", ""),
    ("vers", "Fecske Csaba", "Pici versben pici pék", "1", ""),
    ("vers", "Janina Porazinska", "Varrt cipőt a suszter?", "2", ""),
    ("vers", "Nemes Nagy Ágnes", "Vízimolnár", "1", ""),
])

_t("fold_napja", [
    ("anyanyelvi", None, "Levegő-föld-víz", "123", "Állatokat sorolunk, a gyerekek pedig megmondják, hol élnek. A nagyobbak már maguk is mondhatnak állatot."),
    ("dal", None, "Bújj, bújj", "1", ""),
    ("dal", None, "Csepp, csepp", "1", ""),
    ("dal", None, "Eszterlánc, eszterlánc", "1", ""),
    ("dal", None, "Jöjj ki", "1", ""),
    ("dal", None, "Megy az öreg", "1", ""),
    ("dal", None, "Árkot ugrott", "1", ""),
    ("mese", "Berta Kati", "A Föld meséje", "3", ""),
    ("mese", "Tordon Ákos", "A kismadár kertje", "2", ""),
    ("mese", "Orgoványi Anikó", "Guszti, a giliszta komposztál", "1", ""),
    ("mondoka", None, "Fű, fű, fű", "1", ""),
    ("vers", "Szekér Zsuzsa", "Föld napja", "1", ""),
    ("vers", "Birtha Erzsébet", "Ha nagy leszek", "3", ""),
    ("vers", "Jókai Mór", "Ültess fát!", "2", ""),
])

_t("gyermeknap", [
    ("anyanyelvi", None, "Folytasd a sort!", "123", "Gyümölcsökből kirakott sorozat szabályát felismerve folytatjuk a mintát."),
    ("anyanyelvi", None, "Mondatalkotós", "123", "Két-három tárgyat ábrázoló képet teszünk a gyerekek elé, ők pedig egy mondatba foglalják őket."),
    ("anyanyelvi", None, "Mondd egy szóval!", "123", "Gyűjtőfogalomhoz szavakat sorolunk, vagy fordítva: a gyerek nevezi meg a gyűjtőfogalmat a felsorolt szavakhoz."),
    ("dal", None, "Csivirítem", "1", ""),
    ("dal", None, "Dolgozni szaporán", "3", ""),
    ("dal", None, "Fáj a kutyámnak a lába", "1", ""),
    ("dal", None, "Gyermekek, gyermekek", "1", ""),
    ("dal", None, "Hej, meszelő", "2", ""),
    ("dal", None, "Kicsi üst", "2", ""),
    ("dal", None, "Kőketánc", "3", ""),
    ("dal", None, "Ti csak esztek", "3", ""),
    ("mese", "Benedek Elek", "A három kívánság", "1", ""),
    ("mese", "Zelk Zoltán", "A pipacs és a búzavirág", "3", ""),
    ("nepmese", None, "A levendula", "2", ""),
    ("vers", "Vörös Judit", "A gyermek mosolya", "3", ""),
    ("vers", "Bartos Erika", "Gyümölcskosár", "2", ""),
    ("vers", "Fecske Csaba", "Lepkehívogató", "1", ""),
    ("vers", "Kányádi Sándor", "Somvirág", "2", ""),
    ("vers", "K. László Szilvia", "Nyárköszöntő", "1", ""),
])

_t("husvet", [
    ("anyanyelvi", None, "Csibejáték", "1", "Tányérra apró magvakat szórunk, és a gyerekek kéz nélkül, csak a szájukkal szedegetik fel."),
    ("anyanyelvi", None, "Lopakodó című játék", "23", ""),
    ("dal", None, "Benn a bárány", "23", ""),
    ("dal", None, "Mi szél hozott kis futár", "2", ""),
    ("dal", None, "Mi szél hozott, kis futár", "13", ""),
    ("dal", None, "Nyuszi ül a fűben", "1", ""),
    ("dal", None, "Úgy viruljanak a lányok", "13", ""),
    ("mese", "Zelk Zoltán", "A három nyúl", "1", ""),
    ("mese", "Benedek Elek", "A nyulacska harangocskája", "1", ""),
    ("mese", "Bús Ilona", "Húsvéti tojás", "3", ""),
    ("mese", "Devecser László", "Ki segít a nyuszinak?", "1", ""),
    ("mese", "Enyedi György", "Tojásfestés – bökkenőkkel", "2", ""),
    ("mondoka", None, "Fakadó rügy, szellő hozta", "3", ""),
    ("mondoka", None, "Itt a húsvét, eljött végre", "1", ""),
    ("mondoka", None, "Korán reggel útra keltem", "2", ""),
    ("mondoka", None, "Szabad-e bejönni", "2", ""),
    ("mondoka", None, "Zöld erdőben jártam", "1", ""),
    ("nepmese", None, "Aranyos tarajos kiskakas", "1", ""),
    ("nepmese", None, "Medvecukor és a tavaszi szél", "3", ""),
    ("vers", "Palotai Gyöngyvér", "Húsvét", "3", ""),
    ("vers", None, "Húsvét másodnapján régi szokás szerint", "2", ""),
    ("vers", None, "Jó reggelt, jó reggelt, kedves liliomszál", "3", ""),
])

_t("husveti_het", [
    ("anyanyelvi", None, "Csibejáték", "1", "Tányérra apró magvakat szórunk, és a gyerekek kéz nélkül, csak a szájukkal szedegetik fel."),
    ("anyanyelvi", None, "Lopakodó című játék", "23", ""),
    ("dal", None, "Benn a bárány", "23", ""),
    ("dal", None, "Mi szél hozott kis futár", "2", ""),
    ("dal", None, "Mi szél hozott, kis futár", "13", ""),
    ("dal", None, "Nyuszi ül a fűben", "1", ""),
    ("dal", None, "Úgy viruljanak a lányok", "13", ""),
    ("mese", "Zelk Zoltán", "A három nyúl", "1", ""),
    ("mese", "Benedek Elek", "A nyulacska harangocskája", "1", ""),
    ("mese", "Bús Ilona", "Húsvéti tojás", "3", ""),
    ("mese", "Devecser László", "Ki segít a nyuszinak?", "1", ""),
    ("mese", "Enyedi György", "Tojásfestés – bökkenőkkel", "2", ""),
    ("mondoka", None, "Fakadó rügy, szellő hozta", "3", ""),
    ("mondoka", None, "Itt a húsvét, eljött végre", "1", ""),
    ("mondoka", None, "Korán reggel útra keltem", "2", ""),
    ("mondoka", None, "Szabad-e bejönni", "2", ""),
    ("mondoka", None, "Zöld erdőben jártam", "1", ""),
    ("nepmese", None, "Aranyos tarajos kiskakas", "1", ""),
    ("nepmese", None, "Medvecukor és a tavaszi szél", "3", ""),
    ("vers", "Palotai Gyöngyvér", "Húsvét", "3", ""),
    ("vers", None, "Húsvét másodnapján régi szokás szerint", "2", ""),
    ("vers", None, "Jó reggelt, jó reggelt, kedves liliomszál", "3", ""),
])

_t("karacsony", [
    ("anyanyelvi", None, "A fele sem igaz!", "123", "Olyan mondatot mondunk, amelynek csak az egyik fele igaz, a másik képtelenség. A gyerekek megkeresik a hibát, és helyesen mondják el."),
    ("anyanyelvi", None, "A fele sem igaz! című játék", "2", ""),
    ("anyanyelvi", None, "Gyertyaláng táncoltatása", "123", "A gyertya lángját fújjuk közelebbről és távolabbról, de csak annyira, hogy táncoljon, és el ne aludjon."),
    ("dal", None, "A karácsony", "2", ""),
    ("dal", None, "Báránykának", "1", ""),
    ("dal", None, "Ezüstfenyő", "3", ""),
    ("dal", None, "Hipp, hopp", "3", ""),
    ("dal", None, "Én is pisze", "12", ""),
    ("mese", "Kormos István", "A fázó rókafiak", "1", ""),
    ("mese", "Bartók Julianna", "A hiú hóember", "2", ""),
    ("mese", "Móra Ferenc", "A szánkó", "3", ""),
    ("mondoka", None, "Karácsony", "2", ""),
    ("mondoka", None, "Karácsonyi csengő", "1", ""),
    ("mondoka", None, "Pásztorok", "3", ""),
    ("mondoka", None, "Szálljatok le, szálljatok le", "2", ""),
    ("mondoka", None, "Ég a gyertya, ég", "1", ""),
    ("nepmese", None, "Csillagtallérok", "3", ""),
    ("vers", "K. László Krisztina", "Karácsonyra", "2", ""),
    ("vers", "Fésűs Éva", "Álmodik a fenyőfácska", "3", ""),
])

_t("kodos_oszi_ido", [
    ("anyanyelvi", None, "Papagájjáték", "123", ""),
    ("dal", None, "Esik az eső", "3", ""),
    ("dal", None, "Hopp mókuska", "2", ""),
    ("dal", None, "Tekereg a szél", "1", ""),
    ("dal", None, "Ősz szele zümmög", "3", ""),
    ("nepmese", None, "A fiú meg az északi szélvész", "3", ""),
    ("nepmese", None, "Nagytakarítás a Napnál", "2", ""),
    ("nepmese", None, "Vityilló", "1", ""),
    ("vers", "Kányádi Sándor", "Jön az ősz", "2", ""),
    ("vers", "Szalai Borbála", "Mogyorót szedtem", "1", ""),
    ("vers", "Csanádi Imre", "Négy testvér", "3", ""),
    ("vers", "Osvát Erzsébet", "Útra kelt a nyár", "3", ""),
    ("vers", "Tarbay Ede", "Őszanyó", "3", ""),
    ("vers", "Tordon Ákos", "Őszi mondóka", "2", ""),
    ("vers", "Petrik József", "Őszi szél", "2", ""),
])

_t("kozlekedes", [
    ("anyanyelvi", None, "Melyik jármű hangját hallod?", "12", "Járművek hangját hallgatjuk meg, felismerjük és utánozzuk őket."),
    ("anyanyelvi", None, "Összegyúrt történet c. játék", "3", ""),
    ("dal", None, "János úr készül", "3", ""),
    ("dal", None, "Jön a kocsi", "2", ""),
    ("dal", None, "Kicsi kocsi", "1", ""),
    ("dal", None, "Kocsit, kocsit, komámasszony", "2", ""),
    ("dal", None, "Megy a kocsi", "3", ""),
    ("dal", None, "Most jöttem Bécsből", "3", ""),
    ("dal", None, "Sári néni utazik", "12", ""),
    ("mese", "Malter György", "A dicsekvő versenyautó", "1", ""),
    ("mese", "Várfalvy Emőke", "Az autó és a traktor", "2", ""),
    ("mese", "Donászy Magda", "Tapsi és a villanyrendőr", "3", ""),
    ("vers", "Szalai Borbála", "A jelzőlámpa", "3", ""),
    ("vers", "Weöres Sándor", "Haragosi", "2", ""),
    ("vers", "Weöres Sándor", "Kocsi és vonat", "2", ""),
    ("vers", "Gazdag Erzsi", "Megy a vonat", "3", ""),
    ("vers", "Illyés Gyula", "Mozdony", "1", ""),
    ("vers", "Tóth Elemér", "Vonatosdi", "1", ""),
])

_t("madarvonulas", [
    ("anyanyelvi", None, "Zizievés tányérból", "123", ""),
    ("dal", None, "Egyszer egy erdőben", "3", ""),
    ("dal", None, "Fecskét látok", "2", ""),
    ("dal", None, "Gólya viszi", "1", ""),
    ("dal", None, "Gólya, gólya", "3", ""),
    ("dal", None, "Héja, héja", "2", ""),
    ("mese", "Fésűs Éva", "A büszke tölgyfa", "2", ""),
    ("mese", "Gárdonyi Géza", "A mi gólyánk", "3", ""),
    ("mese", "T. Volgina", "Miért szállnak el a fecskék?", "1", ""),
    ("nepmese", None, "A madarak karácsonya", "2", ""),
    ("vers", "Móra Ferenc", "A cinege cipője", "3", ""),
    ("vers", "Tordon Ákos", "Búcsúzik a gólya", "2", ""),
    ("vers", "Csukás István", "De jó a dió!", "1", ""),
    ("vers", "Kiss Béla", "Nyárutó", "3", ""),
    ("vers", "Pósa Lajos", "Villás farkú fecskék", "1", ""),
    ("vers", "László Gyula", "Ősszel", "2", ""),
])

_t("marcius_15", [
    ("anyanyelvi", None, "Hányat dobbantok?", "23", ""),
    ("dal", None, "Aki nem lép egyszerre", "1", ""),
    ("dal", None, "Fehérvári kapitány", "2", ""),
    ("dal", None, "Gyí, paci, paripa", "1", ""),
    ("dal", None, "Hopp, hopp, katona", "2", ""),
    ("dal", None, "János úr készül", "12", ""),
    ("dal", None, "Rajta, rajta", "2", ""),
    ("dal", None, "Vígan dalol a madár", "2", ""),
    ("mese", "Tordon Ákos", "A csodatrombita", "2", ""),
    ("mondoka", None, "Gyí te fakó, gyí te szürke", "1", ""),
    ("mondoka", None, "Mondóka március 15-re", "1", ""),
    ("mondoka", None, "Paripám csodaszép pejkó", "2", ""),
    ("nepmese", None, "Hogyan lett a huszárnak lova?", "1", ""),
    ("vers", "Sarkady Sándor", "Fel!", "1", ""),
    ("vers", "Weöres Sándor", "Megy az úton", "2", ""),
    ("vers", "Donászy Magda", "Március 15", "3", ""),
    ("vers", "Orgoványi Anikó", "Március 15", "3", ""),
    ("vers", "Drégely László", "Pereg a dob", "2", ""),
    ("vers", "Sarkady Sándor", "Zeneszó leng", "3", ""),
])

_t("marton_nap", [
    ("anyanyelvi", None, "Fújások változatosan", "123", "Libatollat fújunk az asztalon úgy, hogy le ne essen róla. Akadálypályát is építhetünk neki."),
    ("anyanyelvi", None, "Fúvógyakorlat tollpihével", "123", "Felakasztott tollpihét fújunk. A nagyobbak versenyezhetnek, ki bírja tovább egy levegővel, vagy ki ér előbb a szakasz végére."),
    ("anyanyelvi", None, "Hangstaféta", "123", "Félkörben ülünk. Az első gyerek egy levegővel hangoztat egy hangot, ameddig bírja, majd érintéssel adja tovább a szomszédjának. Két csapattal versenyezni is lehet: melyikük jut hosszabb hangokkal a sor végére?"),
    ("dal", None, "Egyél libám", "2", ""),
    ("dal", None, "Elesett a lúd", "3", ""),
    ("dal", None, "Hatan vannak", "3", ""),
    ("dal", None, "Nincs szebb", "1", ""),
    ("dal", None, "Réce ruca", "2", ""),
    ("dal", None, "Száz liba", "3", ""),
    ("mese", "Pákolitz István", "Márton lúdja", "3", ""),
    ("mese", "P. Ábrahám Ernő", "A libák, a farkas meg a kiskakas", "2", ""),
    ("mondoka", None, "Márton-nap (népköltés)", "3", ""),
    ("mondoka", None, "Nincs szebb madár, mint a lúd", "1", ""),
    ("nepmese", None, "A libák és a róka", "1", ""),
    ("vers", "Gazdag Erzsi", "Jóbarátaink", "2", ""),
    ("vers", "Pákolitz István", "Kiolvasó", "3", ""),
    ("vers", "Vershegy Erzsébet", "Libanátha", "2", ""),
    ("vers", "Tordon Ákos", "Libasorban", "3", ""),
    ("vers", None, "Réce, ruca, vadliba, jöjjenek a lagziba", "1", ""),
])

_t("mehek_napja", [
    ("anyanyelvi", None, "Szólánc", "123", "Sorban egymás után szavakat mondunk, amelyeket a következőnek meg kell jegyeznie és megismételnie. Törekszünk olyan szavakra, amelyekből mondat is összeáll."),
    ("anyanyelvi", None, "Valami megváltozott!", "12", "Tavaszhoz, méhekhez kapcsolódó tárgyakat teszünk sorba. Megfigyeljük, majd észrevesszük a változást: cserét, elvételt vagy hozzátételt."),
    ("dal", None, "Elvesztettem zsebkendőmet", "3", ""),
    ("dal", None, "Ilyen cica mellett", "1", ""),
    ("dal", None, "Lóg a lába", "2", ""),
    ("dal", None, "Recse, recse, pogácsa", "2", ""),
    ("dal", None, "Tüzet viszek", "1", ""),
    ("mese", "Móra Ferenc", "A nyughatatlan méhecske", "1", ""),
    ("mese", "Benedek Elek", "Mackó úr meg Ordas koma", "2", ""),
    ("mese", "Stefán Luca", "Mézeskalácsszív", "3", ""),
    ("vers", "Garay János", "A méhecske", "3", ""),
    ("vers", "Móra Ferenc", "Fecskehívogató", "3", ""),
    ("vers", "Donkó László", "Tavasz éke", "23", ""),
])

_t("mihaly_nap", [
    ("anyanyelvi", None, "Mit látsz a képen?", "123", "A kisebbeknek egy képet mutatunk a vásárról, és beszélgetésre hívjuk őket róla. A nagyobbaknak több képet is adhatunk, azokból közösen történetet találunk ki."),
    ("dal", None, "Gyermekek, gyermekek", "1", ""),
    ("dal", None, "Hej, a sályi piacon", "3", ""),
    ("dal", None, "Hipp, hopp", "2", ""),
    ("dal", None, "Én elmentem", "3", ""),
    ("mese", "Benedek Elek", "A csillagszemű juhász", "3", ""),
    ("mese", "Móricz Zsigmond", "A török és a tehenek", "1", ""),
    ("mese", "Illyés Gyula", "Mátyás király meg az igazmondó juhász", "2", ""),
    ("nepmese", None, "A három csibe", "1", ""),
    ("nepmese", None, "A só", "3", ""),
    ("nepmese", None, "Az aranyszőrű bárány", "3", ""),
    ("nepmese", None, "Az állatok nyelvén tudó juhász", "2", ""),
    ("vers", "Osvát Erzsébet", "Balambér", "3", ""),
    ("vers", "Drégely László", "Bohó álom", "1", ""),
    ("vers", "Kányádi Sándor", "Elment Péter", "2", ""),
    ("vers", None, "Kikiáltó: Medvecukor, marcipán", "3", ""),
    ("vers", "Weöres Sándor", "Kutyatár", "2", ""),
    ("vers", "T. Nagy Sándor", "Mókavásár", "2", ""),
    ("vers", "Fecske Csaba", "Nagy vásár volt", "2", ""),
    ("vers", "Weöres Sándor", "Táncnóta", "3", ""),
])

_t("mikulas", [
    ("anyanyelvi", None, "Hol csörög a száncsengő?", "1", "A kisebbek megkeresik a csengés forrását a csoportszobában."),
    ("anyanyelvi", None, "Találós kérdések a télről, Mikulásról", "23", ""),
    ("dal", None, "Apacuka, fundaluka", "3", ""),
    ("dal", None, "Hull a pelyhes", "2", ""),
    ("dal", None, "Itt kopog, ott kopog", "1", ""),
    ("dal", None, "Pattanj pajtás", "3", ""),
    ("dal", "Donászy Magda", "Télapó itt van", "2", ""),
    ("mese", "Petrolay Margit", "Sürgős levél", "2", ""),
    ("mese", "Donászy Magda", "Télapó az erdőben", "2", ""),
    ("nepmese", None, "A télapó kesztyűje", "1", ""),
    ("nepmese", None, "Verses mese", "2", ""),
    ("vers", "Czeglédi Gabriella", "Jön a Mikulás!", "2", ""),
    ("vers", "Mentovics Éva", "Mikulás-köszöntő", "3", ""),
    ("vers", "Donászy Magda", "Télapó", "1", ""),
    ("vers", "Tordon Ákos", "Télapó bundája", "2", ""),
    ("vers", "Móra Ferenc", "Télapó levele, Megjött a télapó", "3", ""),
    ("vers", "Kovács Barbara", "Télapóka", "1", ""),
    ("vers", "Donászy Magda", "Áll a fenyő az erdőben", "1", ""),
])

_t("napszakok_napirend", [
    ("anyanyelvi", None, "Hogy jön sorba?", "123", "Egy kislány napját mutató képeket rakunk sorba. A kisebbek kevesebb képpel dolgoznak, a nagyobbak többel, és történetet is fűzhetnek hozzá."),
    ("dal", None, "A győri Györgynek", "2", ""),
    ("dal", None, "Fussunk, szaladjunk", "1", ""),
    ("dal", None, "Jákobnak volt hat fia", "2", ""),
    ("dal", None, "Pí, pí, pí", "2", ""),
    ("mese", "Gárdonyi Géza", "A cinege", "2", ""),
    ("mese", "Zelk Zoltán", "Hét nap", "3", ""),
    ("mondoka", None, "Hová tegyem a sapkát?", "1", ""),
    ("mondoka", None, "Hétfő, kedd, szerda, csütörtök", "1", ""),
    ("mondoka", None, "Hétfőn egy szem makkot leltem", "2", ""),
    ("mondoka", None, "Hétfőn hentereg, kedden kecmereg", "2", ""),
    ("mondoka", None, "Hétfőn kezdem a hetet", "3", ""),
    ("nepmese", None, "Az öt kismacska", "1", ""),
    ("vers", "Darázs Endre", "Mese a Napról", "3", ""),
    ("vers", "Gazdag Erzsi", "Vendégvárás", "3", ""),
])

_t("osz_kezdete", [
    ("anyanyelvi", None, "Meséld el, mi történt!", "123", "A szüreti mulatságról mesélnek a gyerekek a saját szavaikkal."),
    ("anyanyelvi", None, "Postásjáték", "123", "Sorban ülünk. Az első gyerek fülébe egy szót súgunk, ő továbbadja a szomszédjának, és a sor végén hangosan kimondják, mi jutott el odáig. A kisebbeknek szót, a nagyoknak már rövid mondatot is súghatunk."),
    ("anyanyelvi", None, "Szőlőszemek fújása", "1", ""),
    ("dal", None, "A kálói szőlőbe", "2", ""),
    ("dal", None, "Hüvelykujjam almafa", "1", ""),
    ("dal", None, "Körtéfa, körtéfa", "2", ""),
    ("dal", None, "Lipem, lopom a szőlőt", "1", ""),
    ("dal", None, "Lopják az úr szőlőjét", "3", ""),
    ("dal", None, "Ősz szele zümmög", "3", ""),
    ("mese", "Szutyejev", "Az alma", "1", ""),
    ("mese", "Sebők Éva", "Az alma meg a kerti manó", "3", ""),
    ("mese", "Benedek Elek", "Szegény ember szőlője", "2", ""),
    ("mondoka", None, "Elmúlt a nyár, itt az ősz", "2", ""),
    ("mese", "Benedek Elek", "Szóló szőlő, mosolygó alma, csengő barack", "3", ""),
    ("vers", "Csanádi Imre", "Alma", "12", ""),
    ("vers", "Kányádi Sándor", "Alma, alma", "1", ""),
    ("vers", "Csanádi Imre", "Mókuscsalogató", "1", ""),
    ("vers", "Mentovics Éva", "Szőlő", "3", ""),
    ("vers", "Raggamby András", "Tavasztól tavaszig", "3", ""),
    ("vers", "Sarkadi Sándor", "Édes ősz", "2", ""),
    ("vers", "Fésűs Éva", "Őszi kirándulás", "3", ""),
    ("vers", "Veres Csilla", "Őszi susogó", "3", ""),
])

_t("osz_szinek", [
    ("anyanyelvi", None, "Fúvógyakorlatok terméssel", "123", "Sógyurmából pályát formálunk az asztalon, és fújással vezetjük végig rajta a terméseket."),
    ("dal", None, "Kiszáradt a diófa", "12", ""),
    ("dal", None, "Zörög az erdő", "2", ""),
    ("mondoka", None, "Őszi főzőcske", "3", ""),
    ("nepmese", None, "A három dió", "3", ""),
    ("nepmese", None, "A három kismalac és a farkas", "2", ""),
    ("nepmese", None, "A kiskakas gyémánt félkrajcárja", "1", ""),
    ("nepmese", None, "Az egérke piros szegélyes kabátja", "2", ""),
    ("vers", "Tordon Ákos", "Bolondos mondóka", "3", ""),
    ("vers", "Csoóri Sándor", "Dióbél bácsi", "1", ""),
    ("vers", "Kányádi Sándor", "Jön az ősz", "3", ""),
    ("vers", "Osvát Erzsébet", "Jött őszanyó", "2", ""),
    ("vers", "Kovács Barbara", "Levél a szélben", "1", ""),
    ("vers", "Szalai Borbála", "Makk-emberke", "3", ""),
])

_t("osz_termenyek", [
    ("anyanyelvi", None, "Meséld el, mi történt!", "123", "A szüreti mulatságról mesélnek a gyerekek a saját szavaikkal."),
    ("anyanyelvi", None, "Postásjáték", "123", "Sorban ülünk. Az első gyerek fülébe egy szót súgunk, ő továbbadja a szomszédjának, és a sor végén hangosan kimondják, mi jutott el odáig. A kisebbeknek szót, a nagyoknak már rövid mondatot is súghatunk."),
    ("anyanyelvi", None, "Szőlőszemek fújása", "1", ""),
    ("dal", None, "A kálói szőlőbe", "2", ""),
    ("dal", None, "Hüvelykujjam almafa", "1", ""),
    ("dal", None, "Körtéfa, körtéfa", "2", ""),
    ("dal", None, "Lipem, lopom a szőlőt", "1", ""),
    ("dal", None, "Lopják az úr szőlőjét", "3", ""),
    ("dal", None, "Ősz szele zümmög", "3", ""),
    ("mese", "Szutyejev", "Az alma", "1", ""),
    ("mese", "Sebők Éva", "Az alma meg a kerti manó", "3", ""),
    ("mese", "Benedek Elek", "Szegény ember szőlője", "2", ""),
    ("mondoka", None, "Elmúlt a nyár, itt az ősz", "2", ""),
    ("mese", "Benedek Elek", "Szóló szőlő, mosolygó alma, csengő barack", "3", ""),
    ("vers", "Csanádi Imre", "Alma", "12", ""),
    ("vers", "Kányádi Sándor", "Alma, alma", "1", ""),
    ("vers", "Csanádi Imre", "Mókuscsalogató", "1", ""),
    ("vers", "Mentovics Éva", "Szőlő", "3", ""),
    ("vers", "Raggamby András", "Tavasztól tavaszig", "3", ""),
    ("vers", "Sarkadi Sándor", "Édes ősz", "2", ""),
    ("vers", "Fésűs Éva", "Őszi kirándulás", "3", ""),
    ("vers", "Veres Csilla", "Őszi susogó", "3", ""),
])

_t("osz_zoldsegek", [
    ("anyanyelvi", None, "Hol csörög?", "123", "A kiscsoportosok megkeresik, honnan jön a csörgés. A középsősöknél már bekötjük a szemet, a nagyoknál pedig a párjuk navigálja a keresőt."),
    ("dal", None, "Csicseriborsó, bablencse", "2", ""),
    ("dal", None, "De jó a dió", "2", ""),
    ("dal", None, "Dombon törik a diót", "3", ""),
    ("dal", None, "Itt a köcsög", "1", ""),
    ("dal", None, "Kiszáradt a diófa", "1", ""),
    ("nepmese", None, "A kicsi dió", "2", ""),
    ("nepmese", None, "A nyúl meg a káposzta", "1", ""),
    ("nepmese", None, "A répa", "1", ""),
    ("nepmese", None, "Az égig érő paszuly", "3", ""),
    ("vers", "Apostagi Bolvári Judit", "A kamrában", "3", ""),
    ("vers", "Csukás István", "De jó a dió!", "1", ""),
    ("vers", "Erdélyi József", "Répa, retek, mogyoró", "2", ""),
    ("vers", "Weöres Sándor", "Tündér", "2", ""),
    ("vers", "Osvát Erzsébet", "Utazás", "2", ""),
])

_t("oszi_kerti_munkak", [
    ("anyanyelvi", None, "Kukoricaszemek fújása", "1", ""),
    ("anyanyelvi", None, "Szólánc", "123", "Sorban egymás után szavakat mondunk, amelyeket a következőnek meg kell jegyeznie és megismételnie. Törekszünk olyan szavakra, amelyekből mondat is összeáll."),
    ("dal", None, "Hervad már a lombnak", "3", ""),
    ("dal", None, "Kaszálj, Pista", "2", ""),
    ("dal", None, "Koszorú, koszorú", "12", ""),
    ("dal", None, "Kőketánc", "3", ""),
    ("mese", "Kiss Melinda", "A gesztenyehéj kabátka", "3", ""),
    ("mese", "Benedek Elek", "A kisgömböc", "3", ""),
    ("mondoka", None, "Megfogtam egy magocskát", "1", ""),
    ("nepmese", None, "Mókus Péter kiskertje", "2", ""),
    ("vers", "Radnóti Miklós", "Október", "3", ""),
    ("vers", "Takáts Gyula", "Rigó rúgta dió", "1", ""),
    ("vers", "Galambos Bernadett", "Ősz az erdőn", "3", ""),
    ("vers", "Csanádi Imre", "Őszi levél", "2", ""),
])

_t("tanevkezdes", [
    ("anyanyelvi", None, "Manócska játék", "123", "A nyelv tornáztatása: a nyelv a manócska, aki körbejárja a házát, vagyis a szájat, és megnézi, rendben van-e minden."),
    ("dal", None, "Hipp, hopp, haja hopp", "3", ""),
    ("dal", None, "Koszorú, koszorú", "1", ""),
    ("dal", None, "Szita, szita, sűrű", "2", ""),
    ("dal", None, "Sári néni utazik", "3", ""),
    ("dal", None, "Én is pisze, te is pisze", "1", ""),
    ("mondoka", None, "A piros kabát kalandja", "2", ""),
    ("mondoka", None, "Az aranyos tarajos kiskakas", "3", ""),
    ("vers", "Csukás István", "Dalocska", "2", ""),
    ("vers", "Osvát Erzsébet", "Jött őszanyó", "3", ""),
    ("vers", None, "Gesztenye Gusztika", "1", ""),
])

_t("tavasz", [
    ("anyanyelvi", None, "Ha hallod a hangot, tapsolj!", "123", "Szavakat sorolunk, a gyerekek pedig tapsolnak, valahányszor meghallják az előre megbeszélt hangot."),
    ("anyanyelvi", None, "Kakukktojásjáték", "1", ""),
    ("dal", None, "Bársonyibolyácska", "1", ""),
    ("dal", None, "Ess eső, ess", "1", ""),
    ("dal", None, "Fecskét látok", "1", ""),
    ("dal", None, "Fehér liliomszál", "1", ""),
    ("dal", None, "Gólya viszi a fiát", "1", ""),
    ("dal", None, "Jöjj ki, napocska", "1", ""),
    ("dal", None, "Reggeli harmat", "1", ""),
    ("dal", None, "Süss fel, nap", "1", ""),
    ("mese", "Jékely Zoltán", "A három pillangó", "1", ""),
    ("mese", "Kányádi Sándor", "A kisfiú, aki ibolyát látott", "2", ""),
    ("mese", "Benedek Elek", "Az erdőzöldítő és mezővirágoztató kisasszony", "3", ""),
    ("mondoka", None, "Gyere tavasz, várva várlak", "1", ""),
    ("vers", "Majtényi Erik", "A tavasz", "3", ""),
    ("vers", "Osvát Erzsébet", "Három cimbora", "3", ""),
    ("vers", "Gazdag Erzsi", "Itt a tavasz", "3", ""),
    ("vers", "Csanádi Imre", "Májusdicsérő", "3", ""),
    ("vers", "Drégely László", "Tavasz hívása", "2", ""),
    ("vers", "Csanádi Imre", "Tavasz-ébresztő", "1", ""),
    ("vers", "Csoóri Sándor", "Tavaszi bodzavers", "2", ""),
])

_t("tavaszi_viragok", [
    ("anyanyelvi", None, "Mi van a zsákban?", "123", "Zöldségeket ismerünk fel tapintással, a kézzel érzékelhető tulajdonságaik alapján."),
    ("dal", None, "Fehér liliomszál", "2", ""),
    ("dal", None, "Hová mégy te kis", "13", ""),
    ("dal", None, "Kajcsai rózsa", "2", ""),
    ("dal", None, "Kerekecske", "1", ""),
    ("dal", None, "Kert alatt", "1", ""),
    ("dal", None, "Kinyílt a rózsa", "3", ""),
    ("mese", "Jékely Zoltán", "A három pillangó", "1", ""),
    ("mese", "Zelk Zoltán", "Kecskére bízta a káposztát", "2", ""),
    ("mondoka", None, "Azt mondják a cinegék", "1", ""),
    ("nepmese", None, "A háromágú tölgyfa tündére", "3", "Illyés Gyula gyűjtéséből"),
    ("vers", "Zelk Zoltán", "Csilingel a gyöngyvirág", "3", ""),
    ("vers", "Osvát Erzsébet", "Gyöngyvirág", "3", ""),
    ("vers", "Páskándi Géza", "Konyhakertben, s a kert körül", "2", ""),
])

_t("teli_oltozkodes", [
    ("anyanyelvi", None, "Szívószállal hópehely", "2", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (pingponglabda)", "3", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (vattapamacs)", "1", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (vattapamacs) fújása", "123", "Szívószállal fújjuk végig a vattapamacsot. A kisebbeknek egyenes szakaszon, a nagyobbaknak hullámos pályán."),
    ("dal", None, "Hóember, hóember", "1", ""),
    ("dal", None, "Jákobnak volt hat fia", "2", ""),
    ("dal", None, "Nagy a hó igazán", "2", ""),
    ("dal", None, "Országúton nagy a hó", "2", ""),
    ("mese", "Lengyel Balázs", "A csillagos sün", "1", ""),
    ("mese", "Tóth Anna", "A titokzatos hóember", "3", ""),
    ("mese", "Fésűs Éva", "Télkergető hóvirág", "3", ""),
    ("nepmese", None, "Tél apó", "2", ""),
    ("vers", "Várnai Zseni", "Hull a hó", "2", ""),
    ("vers", "Szalai Borbála", "Hóember", "3", ""),
    ("vers", "Nemes Nagy Ágnes", "Hóesésben", "2", ""),
    ("vers", "Drégely László", "Hógolyózás", "2", ""),
    ("vers", "Orgoványi Anikó", "Januári vacogós", "3", ""),
    ("vers", "Kiss Jenő", "Jégvirág", "3", ""),
    ("vers", "Szalay Borbála", "Mesevilág", "3", ""),
])

_t("teli_sportok", [
    ("anyanyelvi", None, "Szívószállal hópehely", "2", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (pingponglabda)", "3", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (vattapamacs)", "1", ""),
    ("anyanyelvi", None, "Szívószállal hópehely (vattapamacs) fújása", "123", "Szívószállal fújjuk végig a vattapamacsot. A kisebbeknek egyenes szakaszon, a nagyobbaknak hullámos pályán."),
    ("dal", None, "Hóember, hóember", "1", ""),
    ("dal", None, "Jákobnak volt hat fia", "2", ""),
    ("dal", None, "Nagy a hó igazán", "2", ""),
    ("dal", None, "Országúton nagy a hó", "2", ""),
    ("mese", "Lengyel Balázs", "A csillagos sün", "1", ""),
    ("mese", "Tóth Anna", "A titokzatos hóember", "3", ""),
    ("mese", "Fésűs Éva", "Télkergető hóvirág", "3", ""),
    ("nepmese", None, "Tél apó", "2", ""),
    ("vers", "Várnai Zseni", "Hull a hó", "2", ""),
    ("vers", "Szalai Borbála", "Hóember", "3", ""),
    ("vers", "Nemes Nagy Ágnes", "Hóesésben", "2", ""),
    ("vers", "Drégely László", "Hógolyózás", "2", ""),
    ("vers", "Orgoványi Anikó", "Januári vacogós", "3", ""),
    ("vers", "Kiss Jenő", "Jégvirág", "3", ""),
    ("vers", "Szalay Borbála", "Mesevilág", "3", ""),
])

_t("testunk", [
    ("anyanyelvi", None, "Fújások", "123", "Tollpihét vagy pingponglabdát fújunk le az asztalról."),
    ("anyanyelvi", None, "Hova száll a pillangó?", "1", "Mindenki kap egy pillangó ujjbábot, amely arra a testrészre száll, amelyiket mondjuk. Ha jól megy, már csak mutatjuk, és a gyerekek utánozzák."),
    ("anyanyelvi", None, "Találós kérdések az", "3", ""),
    ("anyanyelvi", None, "Találós kérdések az érzékszervekről", "2", ""),
    ("anyanyelvi", None, "Utánozz a tükör előtt!", "123", "A tükör elé állunk egymás mellé. A kisebbek kéz- és lábemelést, integetést, fejbiccentést utánoznak, a nagyobbak hosszabb mozdulatsort."),
    ("dal", None, "Csipp, csepp", "1", ""),
    ("dal", None, "Erre csörög", "1", ""),
    ("dal", None, "Erzsébet asszony", "3", ""),
    ("dal", None, "Esik az eső", "2", ""),
    ("dal", None, "Gólya viszi a fiát", "3", ""),
    ("dal", None, "Lóg a lába", "2", ""),
    ("dal", None, "Rózsa szirma", "3", ""),
    ("dal", None, "Sétálunk", "2", ""),
    ("dal", None, "Áspis kerekes", "2", ""),
    ("dal", None, "Én kis kertet kerteltem", "12", ""),
    ("mese", "Petőfi Sándor", "Arany Lacinak", "2", ""),
    ("mese", "Bogyó és Babóca", "Barátság", "1", ""),
    ("mese", "Fésűs Éva", "Toppantó királykisasszony", "3", ""),
    ("mese", "Sikó-Barabás Eszter", "Öten", "2", ""),
    ("mondoka", None, "Ez a malac piacra megy", "1", ""),
    ("mondoka", None, "Hüvelykujjam almafa", "1", ""),
    ("mondoka", None, "Itt a szemem, itt a szám", "1", ""),
    ("mondoka", None, "Kását főz a kisegér", "1", ""),
    ("mondoka", None, "Két kis madár ül a fán", "1", ""),
    ("mondoka", None, "Mit csinál a kis kezem?", "1", ""),
    ("nepmese", None, "A legérdekesebb játékok", "3", ""),
    ("nepmese", None, "Csupaháj", "3", ""),
    ("nepmese", None, "Málészáj", "3", ""),
    ("nepmese", None, "Nyakigláb", "3", ""),
    ("nepmese", None, "Tíz kicsi barát", "1", ""),
    ("vers", "Mentovics Éva", "Csalafinta történet", "3", ""),
    ("vers", None, "Kerekecske, gombocska, volt egy kicsi dombocska", "2", ""),
    ("vers", "Tordon Ákos", "Kerekecske-gombocska", "3", ""),
    ("vers", "Bódi Irén", "Testrészek", "1", ""),
    ("vers", "Veres Miklós", "Tréfás rajz", "2", ""),
    ("vers", "Bartos Erika", "Tükör", "3", ""),
    ("vers", "Takács Judit", "Ujjszámoló", "1", ""),
])

_t("ujevi_nepszokasok", [
    ("anyanyelvi", None, "Hangstaféta", "23", "Félkörben ülünk. Az első gyerek egy levegővel hangoztat egy hangot, ameddig bírja, majd érintéssel adja tovább a szomszédjának. Két csapattal versenyezni is lehet: melyikük jut hosszabb hangokkal a sor végére?"),
    ("anyanyelvi", None, "Lufiember", "123", "Légzőgyakorlat: lufiemberré válunk. Orron át felfújjuk magunkat, majd a szánkon lassan kiengedjük a levegőt."),
    ("anyanyelvi", None, "Lufiember játék", "1", ""),
    ("dal", None, "A hajnali harangszónak", "3", ""),
    ("dal", None, "Csicseri borsó", "2", ""),
    ("dal", None, "Csicseriborsó", "1", ""),
    ("dal", None, "Fújja szél a", "1", ""),
    ("dal", None, "Hold, hold", "2", ""),
    ("dal", None, "Négy vándor jár", "3", ""),
    ("mese", "Zelk Zoltán", "A jószívű Sajó", "3", ""),
    ("mondoka", None, "Adjon Isten füvet, fát", "12", ""),
    ("mondoka", None, "Bort, búzát, békességet", "3", ""),
    ("mondoka", None, "Kicsi vagyok, székre állok", "1", ""),
    ("nepmese", None, "A kismalac és a farkasok", "1", ""),
    ("nepmese", None, "A kolbász, a béka és az egér", "2", ""),
    ("vers", "Fecske Csaba", "Újévi köszöntő", "2", ""),
    ("vers", "Mentovics Éva", "Újévi köszöntő", "3", ""),
])

_t("viz_vilagnapja", [
    ("anyanyelvi", None, "Kishajó fújása vízen", "123", "Dióhéjból készült hajót fújunk a víz felszínén. A nagyobbak versenyezhetnek, kié ér előbb a kikötőbe."),
    ("dal", None, "Csipp, csepp, egy csepp", "1", ""),
    ("dal", None, "Mit mos, mit mos", "2", ""),
    ("dal", None, "Mély kútba tekintek", "3", ""),
    ("dal", None, "Sándor napján", "3", ""),
    ("dal", None, "Zsipp, zsupp, kenderzsupp", "1", ""),
    ("dal", None, "Én kis kertet kerteltem", "12", ""),
    ("dal", None, "Úszik a kácsa", "2", ""),
    ("mese", "Szutyejev", "A gomba alatt", "2", ""),
    ("mese", "Szutyejev", "A kishajó", "1", ""),
    ("mese", "Benedek Elek", "Hattyú vitéz", "3", ""),
    ("mese", "Zelk Zoltán", "Párácska", "2", ""),
    ("mondoka", None, "Csepp, csepp, esőcsepp", "1", ""),
    ("mondoka", None, "Esik eső csöpörög", "1", ""),
    ("mondoka", None, "Esik eső ja-ja-jaj", "1", ""),
    ("mondoka", None, "Esik, eső uj-jú-jú", "1", ""),
    ("vers", "Orbán Ottó", "A víz", "3", ""),
    ("vers", "Weöres Sándor", "Futózápor", "3", ""),
    ("vers", "Zelk Zoltán", "Halország", "3", ""),
    ("vers", "Osvát Erzsébet", "Irigy felhő", "1", ""),
    ("vers", "Zelk Zoltán", "Kis patak", "2", ""),
    ("vers", "Weöres Sándor", "Tó vize", "2", ""),
])
